export const CANCELLATION_POLICY_CONTENT = {
  heading: 'Cancellation Policy',
  content: `Terms & Conditions <br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer finibus purus eget maximus imperdiet. Cras molestie mattis tortor ac euismod. Nullam rutrum gravida pretium. Donec feugiat a risus at ultrices. Nulla id aliquam quam. Ut id nisi sapien. Mauris suscipit convallis euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc feugiat imperdiet suscipit. Ut sed risus volutpat, consequat quam sit amet, tempor arcu. Etiam maximus, nisl varius efficitur venenatis, elit diam tristique erat, et condimentum mauris nibh et ex. Vestibulum elementum blandit eleifend. Fusce et massa felis.

Ut feugiat erat at elementum sollicitudin. Suspendisse gravida augue ac tellus commodo porta. Pellentesque nisi sem, ultricies sed tempor ut, pharetra in mi. Aliquam vitae odio non nisl suscipit sagittis et nec massa. Maecenas in tincidunt sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Donec orci nulla, eleifend non nisl a, imperdiet malesuada felis.

Pellentesque bibendum nisl quis mauris faucibus interdum. Phasellus sit amet ante non tortor blandit ultricies ac in dolor. Suspendisse vel orci eu mauris porta condimentum quis ut felis. Curabitur blandit interdum elit, vel placerat urna tincidunt at. Morbi porttitor pretium accumsan. Maecenas pharetra nisi ut massa condimentum condimentum. Nullam sit amet nisl a sem tempor feugiat a ut ex. Donec varius mauris faucibus velit pretium interdum. Nulla facilisi. Vivamus imperdiet a nunc vitae molestie. Praesent vulputate malesuada luctus.

Nulla in lobortis tellus, ut feugiat felis. Nam ac fermentum purus, et placerat lectus. Proin massa urna, fermentum sit amet purus sit amet, eleifend commodo dolor. Praesent sed placerat dolor, id maximus nulla. Morbi dapibus enim sit amet est dignissim, id egestas ex varius. Suspendisse velit dolor, lacinia in nunc rhoncus, fermentum mattis justo. Morbi sagittis id risus non tempus.

Suspendisse tempus ornare libero, ac accumsan est aliquam et. Integer ultrices mauris sed commodo pretium. Pellentesque in volutpat velit. Nam laoreet eu nisi consectetur consequat. Vestibulum euismod lorem at ipsum maximus, sed volutpat purus lacinia. Morbi ac lacinia orci, sit amet bibendum turpis. In sed molestie enim. Etiam dictum interdum nibh, vitae suscipit lectus rutrum vitae. Mauris eget vulputate est, sit amet laoreet nulla. Fusce maximus varius erat, vitae tincidunt nisl faucibus vitae. Vivamus at ante ut arcu lobortis cursus. Proin sed convallis neque. Duis suscipit nulla vel nunc tincidunt facilisis. In tincidunt et velit in dignissim. Cras sit amet ante et nisl lobortis consequat. Nunc egestas, augue et feugiat sagittis, quam ex placerat sapien, ac rutrum lorem leo dapibus tellus.`
};
